// Generated by CoffeeScript 1.6.1
(function() {

  $(document).ready(function() {
    $("input.erase").each(function() {
      return $(this).data("default", $(this).val()).addClass("inactive").focus(function() {
        $(this).removeClass("inactive");
        if ($(this).val() === $(this).data("default") || "") {
          return $(this).val("");
        }
      }).blur(function() {
        var default_val;
        default_val = $(this).data("default");
        if ($(this).val() === "") {
          $(this).addClass("inactive");
          return $(this).val($(this).data("default"));
        }
      });
    });
    return $("#signup").on("submit", function(e) {
      var confirmation, email, id, ref, source;
      email = $("#email").val();
      source = $("#source_campaign").val();
      ref = $("#referring_url").val();
      confirmation = $("#confirmation_target").val();
      id = $("#artist_id").val();
      e.preventDefault();
      $("#signup").addClass("loading");
      return $.ajax({
        url: "http://app.topspin.net/api/v1/fan/create_fan",
        type: "POST",
        dataType: "jsonp",
        data: {
          fan: {
            email: email,
            source_campaign: source,
            referring_url: ref,
            confirmation_target: confirmation,
            artist_id: id
          }
        },
        success: function(resp) {
          $("#signup").removeClass("loading");
          $("#email").val("Thanks, Check Your Inbox!");
          return $("#email, #submit").prop("disabled", true);
        }
      });
    });
  });

}).call(this);
